FROM alpine:3.18.6

ENV TELEGRAM_TOKEN abc
ENV TELEGRAM_ADMIN abc
ENV TELEGRAM_GROUP abc
ENV TELEGRAM_NOTIFICATION_CHANNEL abc
ENV TELEGRAM_THREAD 1
ENV CHECK_UPDATES 1
ENV CHECK_UPDATE_EVERY_HOURS 4
ENV CHECK_UPDATE_STOPPED_CONTAINERS 1
ENV CONTAINER_NAME abc
ENV BUTTON_COLUMNS 2
ENV LANGUAGE ES
ENV EXTENDED_MESSAGES 0
ENV TZ UTC

WORKDIR /app

RUN apk add --no-cache python3 py3-pip tzdata npm
COPY requirements.txt /app/requirements.txt
RUN pip3 install -r requirements.txt
RUN npm install -g nodemon

# Legacy watch needed for nodemon to work with docker volumes
ENTRYPOINT ["nodemon", "--legacy-watch", "docker-controller-bot.py"]